- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with AWS"
    DURATION: 120
    ENGINEER: "Dakshina Murthy Nallapati"
  tasks:
  - name: print the varible
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }} , durtion is {{ DURATION }}, Engineer is {{ ENGINEER }}"