- name: variables
  hosts: local
  connection: local
  vars: # Play level variables
    COURSE: "Devops with AWS"
    DURATION: 120
    ENGINEER: "Dakshina Murthy Nallapati"
  tasks:
  - name: print the varible
    vars: # task level variables, accessible with in the tasks only. 
            #Task variables can override the play level variables
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }} , durtion is {{ DURATION }}, Engineer is {{ ENGINEER }}"

  - name: print the varible
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }} , durtion is {{ DURATION }}, Engineer is {{ ENGINEER }}"