- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  taks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Engineer is {{ ENGINEER }}"