- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: Please enter course name
  - name: DURATION
    prompt: Please enter the duration
  - name: ENGINEER 
    prompt: Please end the engineer name
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course name is {{ COURSE }}, Duration is {{ DURATION}}, Engineer name is {{ ENGINEER }}"

