- name: variables from prompt
  hosts: local
  connection: local
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course name is {{ COURSE }}, Duration is {{ DURATION}}, Engineer name is {{ ENGINEER }}"

