
- name: variables prefrence
  hosts: local
  connection: local
  vars: #play level variable
    GREET: "PLAY"
  vars_files:
    - course.yaml
  vars_prompt:
    - name: GREET
      prompt: Enter the value
      private: false
  tasks:
  - name: print course information
      vars:
        GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"

