
- name: variables prefrence
  hosts: local
  connection: local
  # vars: #play level variable
  #   GREET: "PLAY"
  # vars_files:
  #   - course.yaml
  # vars_prompt:
  #   - name: GREET
  #     prompt: Enter the value
  #     private: false
  tasks:
  - name: print the variable
    # vars:
    #   GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"

      #1. Command line or args level
      #2. Task level
      #3. File level
      #4. Prompt level
      #5. Play Level
      #6. Inventory level


