- name: Install nginx
  hosts: web
  become: yes
  tasks:
  - name: intall nginx if RHEL
    ansible.builtin.dnf:
      name: nginx
      state: installed
      enabled: yes
    when: ansible_os_family == "RedHat"

  - name: install nginx if Ubuntu
    ansible.builtin.apt:
      name: nginx
      state: installed
      enabled: yes
    when: ansible_os_family == "Debian"
