- name: loop
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}"
    loop:
    - Dakshina Murthy Nallapati
    - Neeraja Nallapati
    - Lakshmi Priya Nallapati
    - Hasini Nallapati