- name: Install and remove packages
  hosts: web
  become: yes
  tasks:
  - name: Install and remove packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'git', state: 'present' }
    - { name: 'gcc', state: 'absent' }
    - { name: 'mysql', state: 'absent' }
    - { name: 'nginx', state: 'present' }
    - { name: 'zip', state: 'absent' }