- name: Applying filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variables
    ansible.builtin.debug:
      msg: " Hello {{ person | default('Dakshina Murthy N') }} "

  - name: Convert string to list
    vars:
      fruits: "apple banana orange grapes mango"
    ansible.builtin.debug:
      msg: " Fruits are {{ fruits | split(',') }}"