- name: Applying filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variables
    ansible.builtin.debug:
      msg: " Hello {{ person | default('Dakshina Murthy N') }} "

  - name: Convert string to list
    vars:
      fruits: "apple, banana, orange, grapes, mango"
    ansible.builtin.debug:
      msg: " Fruits are {{ fruits | split(',') }}"

  - name: Convert list into map
    vars:
      course:
        name: ansible
        duration: 10hrs
        Engineer: Dakshina Murthy Nallapati
    ansible.builtin.debug:
      msg: "Course details {{ course | dict2items }}"

  - name: Convert map to list
    vars:
      course:
        - {'key': 'name', 'value': 'ansible'}
        - {'key': 'duration', 'value': '10hrs'}
        - {'key': 'Engineer', 'value': 'Dakshina Murthy Nallapati'}
    ansible.builtin.debug:
      msg: "Course details {{ course | items2dict }}"