- name: install nginx software
  #hosts: all
  hosts: web
  become: yes
  #serial: 2
  tasks:
    - name: nginx software installation
      ansible.builtin.package:
        name: nginx
        state: present
    - name: run nginx
      ansible.builtin.service:
        name: nginx
        state: started

